### ISSUE TITLE
Featured Next / current Meal (ongoing): feature preview

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDietProject#138]
Some ideas:
- Next / current meal placed somewhere near to My Points Card;
- If meal is ongoing, a button "Do it now! + NN" will insert the food usage without dialogs.

**Comment by alceurneto** [comment]
Use current button inside `On Going` view.

We could have a button text with 3 lines:
`Some [meal name]`
`+[points]`
`Do it now!`

The first e third lines with a smaller font.

**Comment by alceurneto** [comment]
We need a better layout.
