### ISSUE TITLE
gradle.properties: major, minor and hotfix are not independent pices of information

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDietProject#177]
Our problem:
Today gradle.properties has this snippet:
```
#VERSION CONTROL
major=X
#0 <= minor <= 99
minor=Y
#0 <= hotfix <= 99
hotfix=Z
```
Where X, Y and Z are integers representing current version.

Git identifies changes tracking lines. Only changes in the same line will be pointed as conflicts but changing any line above I'm changing the same information: version number and two parallel changes must be identified as conflict.

The problem is typical: three lines inside the file to represent one piece of information.

A use case when we had issues:
1 - We started the development of new ```0.9.0``` version;
2 - The current version in Play Store has a critical bug. We started to fix it from master (there the version is ```0.8.0``` of course);
3 - The hotfix release will be ```0.8.1``` and line 6 of gradle.properties becomes ```hotfix=1```
4 - The fix was implemented. The new versions is tagged and distributed. Now we need to commit all changes in master to develop solving any conflicts and there is one at least: version ```0.9.0``` X ```0.8.1```.
5 - Sadly, when committing the changes gradle.properties are NOT in conflict and we became with the wrong version ```0.9.1```.

**Comment by alceurneto** [comment]
We could use a one-line implementation:

``` version=X.Y.Z ```

The build class splits the string and calculates the version number.
