### ISSUE TITLE
Roadmap to production: mind map creation

### ISSUE THREAD

**Issue by alceurneto** [ARNdroid/EasyTargetDietProject#190]
Tasks:
- A mind map with features broken by version until first production version. To do this task we need collect information from old maps, current open issues and other features not registered yet;
- Milestones creation based on created roadmap;
- A due date to production version (we expect something by the end of 2015).

**Comment by ARNdroid** [comment]
The mind map is done.

We couldn't establish the due date (some features need to be broken down and we don't have an work schedule yet).
