### ISSUE TITLE
Database backup: create feature

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDietProject#32]
Implement database backup (create and restore) in SD Card.

**Comment by alceurneto** [comment]
I guess we'll have to implement two features here:
- One to allow built in Android Backup Feature;
- One to custom file backup. 

<b>Some research</b>:
Android built in backup:
- http://developer.android.com/guide/topics/data/backup.html
- http://stackoverflow.com/questions/5282936/android-backup-restore-how-to-backup-an-internal-database
- http://www.tutorialspoint.com/android/android_data_backup.htmCustom backup
- http://hxcaine.com/blog/2010/09/14/backing-up-importing-and-restoring-databases-on-android/
- http://stackoverflow.com/questions/13502223/backup-restore-sqlite-db-in-android

**Comment by ARNdroid** [comment]
Android built in backup seems to be a useless feature. For instance, our users cannot see what app data are backed up and they don't know if ETD was backed up or not.

Nevertheless the built in feature seems to have a pretty trivial implementation. Go ahead and do that.

**Comment by alceurneto** [comment]
After more detailed research, I think there is a lot of open questions about using the built in Android Backup for SQLite databases (details here: http://stackoverflow.com/questions/5282936/android-backup-restore-how-to-backup-an-internal-database).

I'll use this issue to implement the original custom backup to SD.

In another issue I'll put the work related with doing  backup in the Android way <b>but only for preference files</b>.
